/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1.1/userguide/building_java_projects.html
 */

plugins {
  application
  jacoco
  id("com.diffplug.spotless") version "6.17.0"
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  // Use JUnit Jupiter for testing.
  testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

  // This dependency is used by the application.
  implementation("com.google.guava:guava:31.1-jre")
  implementation(platform("io.cloudevents:cloudevents-bom:2.4.2"))
  implementation(platform("com.fasterxml.jackson:jackson-bom:2.15.0"))
  implementation("io.cloudevents:cloudevents-protobuf")
  implementation("io.cloudevents:cloudevents-core")
  implementation("io.cloudevents:cloudevents-json-jackson")
  implementation("io.cloudevents:cloudevents-api")
  implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml")
  implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}

application {
  // Define the main class for the application.
  mainClass.set("io.github.aucampia.issue.cejsonstring.App")
}

tasks.named<Test>("test") {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}

java {
  sourceCompatibility = JavaVersion.VERSION_17
  targetCompatibility = JavaVersion.VERSION_17
}

// https://github.com/diffplug/spotless/tree/main/plugin-gradle
spotless {
  java {
    googleJavaFormat().reflowLongStrings(true)
  }
  kotlin {
    ktlint()
  }
  kotlinGradle {
    target("*.gradle.kts")
    ktlint()
  }
}

tasks.withType(JavaCompile::class) {
  options.compilerArgs.addAll(arrayOf("-Xlint:all", "-Werror"))
}
